### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by raxxarr** [GeoffZhu/vue-event-calendar#3]
已经 npm install 过，报错如下，请帮忙看一下，谢谢：
➜  vue-event-calendar git:(master) npm run dev

> vue-event-calendar@1.1.11 dev /Users/youcheng/Desktop/vue-event-calendar
> cross-env NODE_ENV=development webpack-dev-server --open --inline --hot

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack-dev-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by GeoffZhu** [comment]
你是在根目录下，还是在demo目录下？demo目录的代码还没更新 @raxxarr

**Comment by raxxarr** [comment]
根目录下，我 npm install webpack-dev-server -g 就好了，谢谢
